[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Clink-args=-Tsrc/linker.ld"]

[target.riscv64imac-unknown-none-elf]
rustflags = ["-Clink-args=-Tsrc/linker.ld"]